replicaCount: 1

image:
  repository: go-web-app
  pullPolicy: IfNotPresent
  tag: "dev"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "go-web-app"

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532
  fsGroup: 65532
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true

containerPort: 8080

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: go-web-app.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

livenessProbe:
  enabled: true
  path: /healthz
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  enabled: true
  path: /healthz
  initialDelaySeconds: 2
  periodSeconds: 5

resources:
  requests:
    cpu: 25m
    memory: 32Mi
  limits:
    cpu: 250m
    memory: 128Mi
